/* 
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// AbridgedFoodNutrient
    /// </summary>
    [DataContract]
        public partial class AbridgedFoodNutrient :  IEquatable<AbridgedFoodNutrient>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AbridgedFoodNutrient" /> class.
        /// </summary>
        /// <param name="number">number.</param>
        /// <param name="name">name.</param>
        /// <param name="amount">amount.</param>
        /// <param name="unitName">unitName.</param>
        /// <param name="derivationCode">derivationCode.</param>
        /// <param name="derivationDescription">derivationDescription.</param>
        public AbridgedFoodNutrient(int? number = default(int?), string name = default(string), float? amount = default(float?), string unitName = default(string), string derivationCode = default(string), string derivationDescription = default(string))
        {
            this.Number = number;
            this.Name = name;
            this.Amount = amount;
            this.UnitName = unitName;
            this.DerivationCode = derivationCode;
            this.DerivationDescription = derivationDescription;
        }
        
        /// <summary>
        /// Gets or Sets Number
        /// </summary>
        [DataMember(Name="number", EmitDefaultValue=false)]
        public int? Number { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public float? Amount { get; set; }

        /// <summary>
        /// Gets or Sets UnitName
        /// </summary>
        [DataMember(Name="unitName", EmitDefaultValue=false)]
        public string UnitName { get; set; }

        /// <summary>
        /// Gets or Sets DerivationCode
        /// </summary>
        [DataMember(Name="derivationCode", EmitDefaultValue=false)]
        public string DerivationCode { get; set; }

        /// <summary>
        /// Gets or Sets DerivationDescription
        /// </summary>
        [DataMember(Name="derivationDescription", EmitDefaultValue=false)]
        public string DerivationDescription { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AbridgedFoodNutrient {\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  UnitName: ").Append(UnitName).Append("\n");
            sb.Append("  DerivationCode: ").Append(DerivationCode).Append("\n");
            sb.Append("  DerivationDescription: ").Append(DerivationDescription).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AbridgedFoodNutrient);
        }

        /// <summary>
        /// Returns true if AbridgedFoodNutrient instances are equal
        /// </summary>
        /// <param name="input">Instance of AbridgedFoodNutrient to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AbridgedFoodNutrient input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Number == input.Number ||
                    (this.Number != null &&
                    this.Number.Equals(input.Number))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.UnitName == input.UnitName ||
                    (this.UnitName != null &&
                    this.UnitName.Equals(input.UnitName))
                ) && 
                (
                    this.DerivationCode == input.DerivationCode ||
                    (this.DerivationCode != null &&
                    this.DerivationCode.Equals(input.DerivationCode))
                ) && 
                (
                    this.DerivationDescription == input.DerivationDescription ||
                    (this.DerivationDescription != null &&
                    this.DerivationDescription.Equals(input.DerivationDescription))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Number != null)
                    hashCode = hashCode * 59 + this.Number.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.UnitName != null)
                    hashCode = hashCode * 59 + this.UnitName.GetHashCode();
                if (this.DerivationCode != null)
                    hashCode = hashCode * 59 + this.DerivationCode.GetHashCode();
                if (this.DerivationDescription != null)
                    hashCode = hashCode * 59 + this.DerivationDescription.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
