/* 
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// FoodPortion
    /// </summary>
    [DataContract]
        public partial class FoodPortion :  IEquatable<FoodPortion>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FoodPortion" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="amount">amount.</param>
        /// <param name="dataPoints">dataPoints.</param>
        /// <param name="gramWeight">gramWeight.</param>
        /// <param name="minYearAcquired">minYearAcquired.</param>
        /// <param name="modifier">modifier.</param>
        /// <param name="portionDescription">portionDescription.</param>
        /// <param name="sequenceNumber">sequenceNumber.</param>
        /// <param name="measureUnit">measureUnit.</param>
        public FoodPortion(int? id = default(int?), float? amount = default(float?), int? dataPoints = default(int?), float? gramWeight = default(float?), int? minYearAcquired = default(int?), string modifier = default(string), string portionDescription = default(string), int? sequenceNumber = default(int?), MeasureUnit measureUnit = default(MeasureUnit))
        {
            this.Id = id;
            this.Amount = amount;
            this.DataPoints = dataPoints;
            this.GramWeight = gramWeight;
            this.MinYearAcquired = minYearAcquired;
            this.Modifier = modifier;
            this.PortionDescription = portionDescription;
            this.SequenceNumber = sequenceNumber;
            this.MeasureUnit = measureUnit;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public float? Amount { get; set; }

        /// <summary>
        /// Gets or Sets DataPoints
        /// </summary>
        [DataMember(Name="dataPoints", EmitDefaultValue=false)]
        public int? DataPoints { get; set; }

        /// <summary>
        /// Gets or Sets GramWeight
        /// </summary>
        [DataMember(Name="gramWeight", EmitDefaultValue=false)]
        public float? GramWeight { get; set; }

        /// <summary>
        /// Gets or Sets MinYearAcquired
        /// </summary>
        [DataMember(Name="minYearAcquired", EmitDefaultValue=false)]
        public int? MinYearAcquired { get; set; }

        /// <summary>
        /// Gets or Sets Modifier
        /// </summary>
        [DataMember(Name="modifier", EmitDefaultValue=false)]
        public string Modifier { get; set; }

        /// <summary>
        /// Gets or Sets PortionDescription
        /// </summary>
        [DataMember(Name="portionDescription", EmitDefaultValue=false)]
        public string PortionDescription { get; set; }

        /// <summary>
        /// Gets or Sets SequenceNumber
        /// </summary>
        [DataMember(Name="sequenceNumber", EmitDefaultValue=false)]
        public int? SequenceNumber { get; set; }

        /// <summary>
        /// Gets or Sets MeasureUnit
        /// </summary>
        [DataMember(Name="measureUnit", EmitDefaultValue=false)]
        public MeasureUnit MeasureUnit { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FoodPortion {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  DataPoints: ").Append(DataPoints).Append("\n");
            sb.Append("  GramWeight: ").Append(GramWeight).Append("\n");
            sb.Append("  MinYearAcquired: ").Append(MinYearAcquired).Append("\n");
            sb.Append("  Modifier: ").Append(Modifier).Append("\n");
            sb.Append("  PortionDescription: ").Append(PortionDescription).Append("\n");
            sb.Append("  SequenceNumber: ").Append(SequenceNumber).Append("\n");
            sb.Append("  MeasureUnit: ").Append(MeasureUnit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FoodPortion);
        }

        /// <summary>
        /// Returns true if FoodPortion instances are equal
        /// </summary>
        /// <param name="input">Instance of FoodPortion to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FoodPortion input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.DataPoints == input.DataPoints ||
                    (this.DataPoints != null &&
                    this.DataPoints.Equals(input.DataPoints))
                ) && 
                (
                    this.GramWeight == input.GramWeight ||
                    (this.GramWeight != null &&
                    this.GramWeight.Equals(input.GramWeight))
                ) && 
                (
                    this.MinYearAcquired == input.MinYearAcquired ||
                    (this.MinYearAcquired != null &&
                    this.MinYearAcquired.Equals(input.MinYearAcquired))
                ) && 
                (
                    this.Modifier == input.Modifier ||
                    (this.Modifier != null &&
                    this.Modifier.Equals(input.Modifier))
                ) && 
                (
                    this.PortionDescription == input.PortionDescription ||
                    (this.PortionDescription != null &&
                    this.PortionDescription.Equals(input.PortionDescription))
                ) && 
                (
                    this.SequenceNumber == input.SequenceNumber ||
                    (this.SequenceNumber != null &&
                    this.SequenceNumber.Equals(input.SequenceNumber))
                ) && 
                (
                    this.MeasureUnit == input.MeasureUnit ||
                    (this.MeasureUnit != null &&
                    this.MeasureUnit.Equals(input.MeasureUnit))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.DataPoints != null)
                    hashCode = hashCode * 59 + this.DataPoints.GetHashCode();
                if (this.GramWeight != null)
                    hashCode = hashCode * 59 + this.GramWeight.GetHashCode();
                if (this.MinYearAcquired != null)
                    hashCode = hashCode * 59 + this.MinYearAcquired.GetHashCode();
                if (this.Modifier != null)
                    hashCode = hashCode * 59 + this.Modifier.GetHashCode();
                if (this.PortionDescription != null)
                    hashCode = hashCode * 59 + this.PortionDescription.GetHashCode();
                if (this.SequenceNumber != null)
                    hashCode = hashCode * 59 + this.SequenceNumber.GetHashCode();
                if (this.MeasureUnit != null)
                    hashCode = hashCode * 59 + this.MeasureUnit.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
