/* 
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// FoodComponent
    /// </summary>
    [DataContract]
        public partial class FoodComponent :  IEquatable<FoodComponent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FoodComponent" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="dataPoints">dataPoints.</param>
        /// <param name="gramWeight">gramWeight.</param>
        /// <param name="isRefuse">isRefuse.</param>
        /// <param name="minYearAcquired">minYearAcquired.</param>
        /// <param name="percentWeight">percentWeight.</param>
        public FoodComponent(int? id = default(int?), string name = default(string), int? dataPoints = default(int?), decimal? gramWeight = default(decimal?), bool? isRefuse = default(bool?), int? minYearAcquired = default(int?), decimal? percentWeight = default(decimal?))
        {
            this.Id = id;
            this.Name = name;
            this.DataPoints = dataPoints;
            this.GramWeight = gramWeight;
            this.IsRefuse = isRefuse;
            this.MinYearAcquired = minYearAcquired;
            this.PercentWeight = percentWeight;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets DataPoints
        /// </summary>
        [DataMember(Name="dataPoints", EmitDefaultValue=false)]
        public int? DataPoints { get; set; }

        /// <summary>
        /// Gets or Sets GramWeight
        /// </summary>
        [DataMember(Name="gramWeight", EmitDefaultValue=false)]
        public decimal? GramWeight { get; set; }

        /// <summary>
        /// Gets or Sets IsRefuse
        /// </summary>
        [DataMember(Name="isRefuse", EmitDefaultValue=false)]
        public bool? IsRefuse { get; set; }

        /// <summary>
        /// Gets or Sets MinYearAcquired
        /// </summary>
        [DataMember(Name="minYearAcquired", EmitDefaultValue=false)]
        public int? MinYearAcquired { get; set; }

        /// <summary>
        /// Gets or Sets PercentWeight
        /// </summary>
        [DataMember(Name="percentWeight", EmitDefaultValue=false)]
        public decimal? PercentWeight { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FoodComponent {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  DataPoints: ").Append(DataPoints).Append("\n");
            sb.Append("  GramWeight: ").Append(GramWeight).Append("\n");
            sb.Append("  IsRefuse: ").Append(IsRefuse).Append("\n");
            sb.Append("  MinYearAcquired: ").Append(MinYearAcquired).Append("\n");
            sb.Append("  PercentWeight: ").Append(PercentWeight).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FoodComponent);
        }

        /// <summary>
        /// Returns true if FoodComponent instances are equal
        /// </summary>
        /// <param name="input">Instance of FoodComponent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FoodComponent input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.DataPoints == input.DataPoints ||
                    (this.DataPoints != null &&
                    this.DataPoints.Equals(input.DataPoints))
                ) && 
                (
                    this.GramWeight == input.GramWeight ||
                    (this.GramWeight != null &&
                    this.GramWeight.Equals(input.GramWeight))
                ) && 
                (
                    this.IsRefuse == input.IsRefuse ||
                    (this.IsRefuse != null &&
                    this.IsRefuse.Equals(input.IsRefuse))
                ) && 
                (
                    this.MinYearAcquired == input.MinYearAcquired ||
                    (this.MinYearAcquired != null &&
                    this.MinYearAcquired.Equals(input.MinYearAcquired))
                ) && 
                (
                    this.PercentWeight == input.PercentWeight ||
                    (this.PercentWeight != null &&
                    this.PercentWeight.Equals(input.PercentWeight))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.DataPoints != null)
                    hashCode = hashCode * 59 + this.DataPoints.GetHashCode();
                if (this.GramWeight != null)
                    hashCode = hashCode * 59 + this.GramWeight.GetHashCode();
                if (this.IsRefuse != null)
                    hashCode = hashCode * 59 + this.IsRefuse.GetHashCode();
                if (this.MinYearAcquired != null)
                    hashCode = hashCode * 59 + this.MinYearAcquired.GetHashCode();
                if (this.PercentWeight != null)
                    hashCode = hashCode * 59 + this.PercentWeight.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
