/* 
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// NutrientAnalysisDetails
    /// </summary>
    [DataContract]
        public partial class NutrientAnalysisDetails :  IEquatable<NutrientAnalysisDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NutrientAnalysisDetails" /> class.
        /// </summary>
        /// <param name="subSampleId">subSampleId.</param>
        /// <param name="amount">amount.</param>
        /// <param name="nutrientId">nutrientId.</param>
        /// <param name="labMethodDescription">labMethodDescription.</param>
        /// <param name="labMethodOriginalDescription">labMethodOriginalDescription.</param>
        /// <param name="labMethodLink">labMethodLink.</param>
        /// <param name="labMethodTechnique">labMethodTechnique.</param>
        /// <param name="nutrientAcquisitionDetails">nutrientAcquisitionDetails.</param>
        public NutrientAnalysisDetails(int? subSampleId = default(int?), float? amount = default(float?), int? nutrientId = default(int?), string labMethodDescription = default(string), string labMethodOriginalDescription = default(string), string labMethodLink = default(string), string labMethodTechnique = default(string), List<NutrientAcquisitionDetails> nutrientAcquisitionDetails = default(List<NutrientAcquisitionDetails>))
        {
            this.SubSampleId = subSampleId;
            this.Amount = amount;
            this.NutrientId = nutrientId;
            this.LabMethodDescription = labMethodDescription;
            this.LabMethodOriginalDescription = labMethodOriginalDescription;
            this.LabMethodLink = labMethodLink;
            this.LabMethodTechnique = labMethodTechnique;
            this.NutrientAcquisitionDetails = nutrientAcquisitionDetails;
        }
        
        /// <summary>
        /// Gets or Sets SubSampleId
        /// </summary>
        [DataMember(Name="subSampleId", EmitDefaultValue=false)]
        public int? SubSampleId { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public float? Amount { get; set; }

        /// <summary>
        /// Gets or Sets NutrientId
        /// </summary>
        [DataMember(Name="nutrientId", EmitDefaultValue=false)]
        public int? NutrientId { get; set; }

        /// <summary>
        /// Gets or Sets LabMethodDescription
        /// </summary>
        [DataMember(Name="labMethodDescription", EmitDefaultValue=false)]
        public string LabMethodDescription { get; set; }

        /// <summary>
        /// Gets or Sets LabMethodOriginalDescription
        /// </summary>
        [DataMember(Name="labMethodOriginalDescription", EmitDefaultValue=false)]
        public string LabMethodOriginalDescription { get; set; }

        /// <summary>
        /// Gets or Sets LabMethodLink
        /// </summary>
        [DataMember(Name="labMethodLink", EmitDefaultValue=false)]
        public string LabMethodLink { get; set; }

        /// <summary>
        /// Gets or Sets LabMethodTechnique
        /// </summary>
        [DataMember(Name="labMethodTechnique", EmitDefaultValue=false)]
        public string LabMethodTechnique { get; set; }

        /// <summary>
        /// Gets or Sets NutrientAcquisitionDetails
        /// </summary>
        [DataMember(Name="nutrientAcquisitionDetails", EmitDefaultValue=false)]
        public List<NutrientAcquisitionDetails> NutrientAcquisitionDetails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NutrientAnalysisDetails {\n");
            sb.Append("  SubSampleId: ").Append(SubSampleId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  NutrientId: ").Append(NutrientId).Append("\n");
            sb.Append("  LabMethodDescription: ").Append(LabMethodDescription).Append("\n");
            sb.Append("  LabMethodOriginalDescription: ").Append(LabMethodOriginalDescription).Append("\n");
            sb.Append("  LabMethodLink: ").Append(LabMethodLink).Append("\n");
            sb.Append("  LabMethodTechnique: ").Append(LabMethodTechnique).Append("\n");
            sb.Append("  NutrientAcquisitionDetails: ").Append(NutrientAcquisitionDetails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NutrientAnalysisDetails);
        }

        /// <summary>
        /// Returns true if NutrientAnalysisDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of NutrientAnalysisDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NutrientAnalysisDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SubSampleId == input.SubSampleId ||
                    (this.SubSampleId != null &&
                    this.SubSampleId.Equals(input.SubSampleId))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.NutrientId == input.NutrientId ||
                    (this.NutrientId != null &&
                    this.NutrientId.Equals(input.NutrientId))
                ) && 
                (
                    this.LabMethodDescription == input.LabMethodDescription ||
                    (this.LabMethodDescription != null &&
                    this.LabMethodDescription.Equals(input.LabMethodDescription))
                ) && 
                (
                    this.LabMethodOriginalDescription == input.LabMethodOriginalDescription ||
                    (this.LabMethodOriginalDescription != null &&
                    this.LabMethodOriginalDescription.Equals(input.LabMethodOriginalDescription))
                ) && 
                (
                    this.LabMethodLink == input.LabMethodLink ||
                    (this.LabMethodLink != null &&
                    this.LabMethodLink.Equals(input.LabMethodLink))
                ) && 
                (
                    this.LabMethodTechnique == input.LabMethodTechnique ||
                    (this.LabMethodTechnique != null &&
                    this.LabMethodTechnique.Equals(input.LabMethodTechnique))
                ) && 
                (
                    this.NutrientAcquisitionDetails == input.NutrientAcquisitionDetails ||
                    this.NutrientAcquisitionDetails != null &&
                    input.NutrientAcquisitionDetails != null &&
                    this.NutrientAcquisitionDetails.SequenceEqual(input.NutrientAcquisitionDetails)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SubSampleId != null)
                    hashCode = hashCode * 59 + this.SubSampleId.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.NutrientId != null)
                    hashCode = hashCode * 59 + this.NutrientId.GetHashCode();
                if (this.LabMethodDescription != null)
                    hashCode = hashCode * 59 + this.LabMethodDescription.GetHashCode();
                if (this.LabMethodOriginalDescription != null)
                    hashCode = hashCode * 59 + this.LabMethodOriginalDescription.GetHashCode();
                if (this.LabMethodLink != null)
                    hashCode = hashCode * 59 + this.LabMethodLink.GetHashCode();
                if (this.LabMethodTechnique != null)
                    hashCode = hashCode * 59 + this.LabMethodTechnique.GetHashCode();
                if (this.NutrientAcquisitionDetails != null)
                    hashCode = hashCode * 59 + this.NutrientAcquisitionDetails.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
