/* 
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// SurveyFoodItem
    /// </summary>
    [DataContract]
        public partial class SurveyFoodItem :  IEquatable<SurveyFoodItem>, IValidatableObject, InlineResponse200 
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SurveyFoodItem" /> class.
        /// </summary>
        /// <param name="fdcId">fdcId (required).</param>
        /// <param name="datatype">datatype.</param>
        /// <param name="description">description (required).</param>
        /// <param name="endDate">endDate.</param>
        /// <param name="foodClass">foodClass.</param>
        /// <param name="foodCode">foodCode.</param>
        /// <param name="publicationDate">publicationDate.</param>
        /// <param name="startDate">startDate.</param>
        /// <param name="foodAttributes">foodAttributes.</param>
        /// <param name="foodPortions">foodPortions.</param>
        /// <param name="inputFoods">inputFoods.</param>
        /// <param name="wweiaFoodCategory">wweiaFoodCategory.</param>
        public SurveyFoodItem(int? fdcId = default(int?), string datatype = default(string), string description = default(string), string endDate = default(string), string foodClass = default(string), string foodCode = default(string), string publicationDate = default(string), string startDate = default(string), List<FoodAttribute> foodAttributes = default(List<FoodAttribute>), List<FoodPortion> foodPortions = default(List<FoodPortion>), List<InputFoodSurvey> inputFoods = default(List<InputFoodSurvey>), WweiaFoodCategory wweiaFoodCategory = default(WweiaFoodCategory))
        {
            // to ensure "fdcId" is required (not null)
            if (fdcId == null)
            {
                throw new InvalidDataException("fdcId is a required property for SurveyFoodItem and cannot be null");
            }
            else
            {
                this.FdcId = fdcId;
            }
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new InvalidDataException("description is a required property for SurveyFoodItem and cannot be null");
            }
            else
            {
                this.Description = description;
            }
            this.Datatype = datatype;
            this.EndDate = endDate;
            this.FoodClass = foodClass;
            this.FoodCode = foodCode;
            this.PublicationDate = publicationDate;
            this.StartDate = startDate;
            this.FoodAttributes = foodAttributes;
            this.FoodPortions = foodPortions;
            this.InputFoods = inputFoods;
            this.WweiaFoodCategory = wweiaFoodCategory;
        }
        
        /// <summary>
        /// Gets or Sets FdcId
        /// </summary>
        [DataMember(Name="fdcId", EmitDefaultValue=false)]
        public int? FdcId { get; set; }

        /// <summary>
        /// Gets or Sets Datatype
        /// </summary>
        [DataMember(Name="datatype", EmitDefaultValue=false)]
        public string Datatype { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets EndDate
        /// </summary>
        [DataMember(Name="endDate", EmitDefaultValue=false)]
        public string EndDate { get; set; }

        /// <summary>
        /// Gets or Sets FoodClass
        /// </summary>
        [DataMember(Name="foodClass", EmitDefaultValue=false)]
        public string FoodClass { get; set; }

        /// <summary>
        /// Gets or Sets FoodCode
        /// </summary>
        [DataMember(Name="foodCode", EmitDefaultValue=false)]
        public string FoodCode { get; set; }

        /// <summary>
        /// Gets or Sets PublicationDate
        /// </summary>
        [DataMember(Name="publicationDate", EmitDefaultValue=false)]
        public string PublicationDate { get; set; }

        /// <summary>
        /// Gets or Sets StartDate
        /// </summary>
        [DataMember(Name="startDate", EmitDefaultValue=false)]
        public string StartDate { get; set; }

        /// <summary>
        /// Gets or Sets FoodAttributes
        /// </summary>
        [DataMember(Name="foodAttributes", EmitDefaultValue=false)]
        public List<FoodAttribute> FoodAttributes { get; set; }

        /// <summary>
        /// Gets or Sets FoodPortions
        /// </summary>
        [DataMember(Name="foodPortions", EmitDefaultValue=false)]
        public List<FoodPortion> FoodPortions { get; set; }

        /// <summary>
        /// Gets or Sets InputFoods
        /// </summary>
        [DataMember(Name="inputFoods", EmitDefaultValue=false)]
        public List<InputFoodSurvey> InputFoods { get; set; }

        /// <summary>
        /// Gets or Sets WweiaFoodCategory
        /// </summary>
        [DataMember(Name="wweiaFoodCategory", EmitDefaultValue=false)]
        public WweiaFoodCategory WweiaFoodCategory { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SurveyFoodItem {\n");
            sb.Append("  FdcId: ").Append(FdcId).Append("\n");
            sb.Append("  Datatype: ").Append(Datatype).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  EndDate: ").Append(EndDate).Append("\n");
            sb.Append("  FoodClass: ").Append(FoodClass).Append("\n");
            sb.Append("  FoodCode: ").Append(FoodCode).Append("\n");
            sb.Append("  PublicationDate: ").Append(PublicationDate).Append("\n");
            sb.Append("  StartDate: ").Append(StartDate).Append("\n");
            sb.Append("  FoodAttributes: ").Append(FoodAttributes).Append("\n");
            sb.Append("  FoodPortions: ").Append(FoodPortions).Append("\n");
            sb.Append("  InputFoods: ").Append(InputFoods).Append("\n");
            sb.Append("  WweiaFoodCategory: ").Append(WweiaFoodCategory).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SurveyFoodItem);
        }

        /// <summary>
        /// Returns true if SurveyFoodItem instances are equal
        /// </summary>
        /// <param name="input">Instance of SurveyFoodItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SurveyFoodItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FdcId == input.FdcId ||
                    (this.FdcId != null &&
                    this.FdcId.Equals(input.FdcId))
                ) && 
                (
                    this.Datatype == input.Datatype ||
                    (this.Datatype != null &&
                    this.Datatype.Equals(input.Datatype))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.EndDate == input.EndDate ||
                    (this.EndDate != null &&
                    this.EndDate.Equals(input.EndDate))
                ) && 
                (
                    this.FoodClass == input.FoodClass ||
                    (this.FoodClass != null &&
                    this.FoodClass.Equals(input.FoodClass))
                ) && 
                (
                    this.FoodCode == input.FoodCode ||
                    (this.FoodCode != null &&
                    this.FoodCode.Equals(input.FoodCode))
                ) && 
                (
                    this.PublicationDate == input.PublicationDate ||
                    (this.PublicationDate != null &&
                    this.PublicationDate.Equals(input.PublicationDate))
                ) && 
                (
                    this.StartDate == input.StartDate ||
                    (this.StartDate != null &&
                    this.StartDate.Equals(input.StartDate))
                ) && 
                (
                    this.FoodAttributes == input.FoodAttributes ||
                    this.FoodAttributes != null &&
                    input.FoodAttributes != null &&
                    this.FoodAttributes.SequenceEqual(input.FoodAttributes)
                ) && 
                (
                    this.FoodPortions == input.FoodPortions ||
                    this.FoodPortions != null &&
                    input.FoodPortions != null &&
                    this.FoodPortions.SequenceEqual(input.FoodPortions)
                ) && 
                (
                    this.InputFoods == input.InputFoods ||
                    this.InputFoods != null &&
                    input.InputFoods != null &&
                    this.InputFoods.SequenceEqual(input.InputFoods)
                ) && 
                (
                    this.WweiaFoodCategory == input.WweiaFoodCategory ||
                    (this.WweiaFoodCategory != null &&
                    this.WweiaFoodCategory.Equals(input.WweiaFoodCategory))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FdcId != null)
                    hashCode = hashCode * 59 + this.FdcId.GetHashCode();
                if (this.Datatype != null)
                    hashCode = hashCode * 59 + this.Datatype.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.EndDate != null)
                    hashCode = hashCode * 59 + this.EndDate.GetHashCode();
                if (this.FoodClass != null)
                    hashCode = hashCode * 59 + this.FoodClass.GetHashCode();
                if (this.FoodCode != null)
                    hashCode = hashCode * 59 + this.FoodCode.GetHashCode();
                if (this.PublicationDate != null)
                    hashCode = hashCode * 59 + this.PublicationDate.GetHashCode();
                if (this.StartDate != null)
                    hashCode = hashCode * 59 + this.StartDate.GetHashCode();
                if (this.FoodAttributes != null)
                    hashCode = hashCode * 59 + this.FoodAttributes.GetHashCode();
                if (this.FoodPortions != null)
                    hashCode = hashCode * 59 + this.FoodPortions.GetHashCode();
                if (this.InputFoods != null)
                    hashCode = hashCode * 59 + this.InputFoods.GetHashCode();
                if (this.WweiaFoodCategory != null)
                    hashCode = hashCode * 59 + this.WweiaFoodCategory.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
