/* 
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BrandedFoodItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BrandedFoodItemTests
    {
        // TODO uncomment below to declare an instance variable for BrandedFoodItem
        //private BrandedFoodItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BrandedFoodItem
            //instance = new BrandedFoodItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BrandedFoodItem
        /// </summary>
        [Test]
        public void BrandedFoodItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BrandedFoodItem
            //Assert.IsInstanceOfType<BrandedFoodItem> (instance, "variable 'instance' is a BrandedFoodItem");
        }


        /// <summary>
        /// Test the property 'FdcId'
        /// </summary>
        [Test]
        public void FdcIdTest()
        {
            // TODO unit test for the property 'FdcId'
        }
        /// <summary>
        /// Test the property 'AvailableDate'
        /// </summary>
        [Test]
        public void AvailableDateTest()
        {
            // TODO unit test for the property 'AvailableDate'
        }
        /// <summary>
        /// Test the property 'BrandOwner'
        /// </summary>
        [Test]
        public void BrandOwnerTest()
        {
            // TODO unit test for the property 'BrandOwner'
        }
        /// <summary>
        /// Test the property 'DataSource'
        /// </summary>
        [Test]
        public void DataSourceTest()
        {
            // TODO unit test for the property 'DataSource'
        }
        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Test]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'FoodClass'
        /// </summary>
        [Test]
        public void FoodClassTest()
        {
            // TODO unit test for the property 'FoodClass'
        }
        /// <summary>
        /// Test the property 'GtinUpc'
        /// </summary>
        [Test]
        public void GtinUpcTest()
        {
            // TODO unit test for the property 'GtinUpc'
        }
        /// <summary>
        /// Test the property 'HouseholdServingFullText'
        /// </summary>
        [Test]
        public void HouseholdServingFullTextTest()
        {
            // TODO unit test for the property 'HouseholdServingFullText'
        }
        /// <summary>
        /// Test the property 'Ingredients'
        /// </summary>
        [Test]
        public void IngredientsTest()
        {
            // TODO unit test for the property 'Ingredients'
        }
        /// <summary>
        /// Test the property 'ModifiedDate'
        /// </summary>
        [Test]
        public void ModifiedDateTest()
        {
            // TODO unit test for the property 'ModifiedDate'
        }
        /// <summary>
        /// Test the property 'PublicationDate'
        /// </summary>
        [Test]
        public void PublicationDateTest()
        {
            // TODO unit test for the property 'PublicationDate'
        }
        /// <summary>
        /// Test the property 'ServingSize'
        /// </summary>
        [Test]
        public void ServingSizeTest()
        {
            // TODO unit test for the property 'ServingSize'
        }
        /// <summary>
        /// Test the property 'ServingSizeUnit'
        /// </summary>
        [Test]
        public void ServingSizeUnitTest()
        {
            // TODO unit test for the property 'ServingSizeUnit'
        }
        /// <summary>
        /// Test the property 'PreparationStateCode'
        /// </summary>
        [Test]
        public void PreparationStateCodeTest()
        {
            // TODO unit test for the property 'PreparationStateCode'
        }
        /// <summary>
        /// Test the property 'BrandedFoodCategory'
        /// </summary>
        [Test]
        public void BrandedFoodCategoryTest()
        {
            // TODO unit test for the property 'BrandedFoodCategory'
        }
        /// <summary>
        /// Test the property 'TradeChannel'
        /// </summary>
        [Test]
        public void TradeChannelTest()
        {
            // TODO unit test for the property 'TradeChannel'
        }
        /// <summary>
        /// Test the property 'GpcClassCode'
        /// </summary>
        [Test]
        public void GpcClassCodeTest()
        {
            // TODO unit test for the property 'GpcClassCode'
        }
        /// <summary>
        /// Test the property 'FoodNutrients'
        /// </summary>
        [Test]
        public void FoodNutrientsTest()
        {
            // TODO unit test for the property 'FoodNutrients'
        }
        /// <summary>
        /// Test the property 'FoodUpdateLog'
        /// </summary>
        [Test]
        public void FoodUpdateLogTest()
        {
            // TODO unit test for the property 'FoodUpdateLog'
        }
        /// <summary>
        /// Test the property 'LabelNutrients'
        /// </summary>
        [Test]
        public void LabelNutrientsTest()
        {
            // TODO unit test for the property 'LabelNutrients'
        }

    }

}
