/* 
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BrandedFoodItemLabelNutrients
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BrandedFoodItemLabelNutrientsTests
    {
        // TODO uncomment below to declare an instance variable for BrandedFoodItemLabelNutrients
        //private BrandedFoodItemLabelNutrients instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BrandedFoodItemLabelNutrients
            //instance = new BrandedFoodItemLabelNutrients();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BrandedFoodItemLabelNutrients
        /// </summary>
        [Test]
        public void BrandedFoodItemLabelNutrientsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BrandedFoodItemLabelNutrients
            //Assert.IsInstanceOfType<BrandedFoodItemLabelNutrients> (instance, "variable 'instance' is a BrandedFoodItemLabelNutrients");
        }


        /// <summary>
        /// Test the property 'Fat'
        /// </summary>
        [Test]
        public void FatTest()
        {
            // TODO unit test for the property 'Fat'
        }
        /// <summary>
        /// Test the property 'SaturatedFat'
        /// </summary>
        [Test]
        public void SaturatedFatTest()
        {
            // TODO unit test for the property 'SaturatedFat'
        }
        /// <summary>
        /// Test the property 'TransFat'
        /// </summary>
        [Test]
        public void TransFatTest()
        {
            // TODO unit test for the property 'TransFat'
        }
        /// <summary>
        /// Test the property 'Cholesterol'
        /// </summary>
        [Test]
        public void CholesterolTest()
        {
            // TODO unit test for the property 'Cholesterol'
        }
        /// <summary>
        /// Test the property 'Sodium'
        /// </summary>
        [Test]
        public void SodiumTest()
        {
            // TODO unit test for the property 'Sodium'
        }
        /// <summary>
        /// Test the property 'Carbohydrates'
        /// </summary>
        [Test]
        public void CarbohydratesTest()
        {
            // TODO unit test for the property 'Carbohydrates'
        }
        /// <summary>
        /// Test the property 'Fiber'
        /// </summary>
        [Test]
        public void FiberTest()
        {
            // TODO unit test for the property 'Fiber'
        }
        /// <summary>
        /// Test the property 'Sugars'
        /// </summary>
        [Test]
        public void SugarsTest()
        {
            // TODO unit test for the property 'Sugars'
        }
        /// <summary>
        /// Test the property 'Protein'
        /// </summary>
        [Test]
        public void ProteinTest()
        {
            // TODO unit test for the property 'Protein'
        }
        /// <summary>
        /// Test the property 'Calcium'
        /// </summary>
        [Test]
        public void CalciumTest()
        {
            // TODO unit test for the property 'Calcium'
        }
        /// <summary>
        /// Test the property 'Iron'
        /// </summary>
        [Test]
        public void IronTest()
        {
            // TODO unit test for the property 'Iron'
        }
        /// <summary>
        /// Test the property 'Potassium'
        /// </summary>
        [Test]
        public void PotassiumTest()
        {
            // TODO unit test for the property 'Potassium'
        }
        /// <summary>
        /// Test the property 'Calories'
        /// </summary>
        [Test]
        public void CaloriesTest()
        {
            // TODO unit test for the property 'Calories'
        }

    }

}
