/* 
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FoodPortion
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FoodPortionTests
    {
        // TODO uncomment below to declare an instance variable for FoodPortion
        //private FoodPortion instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FoodPortion
            //instance = new FoodPortion();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FoodPortion
        /// </summary>
        [Test]
        public void FoodPortionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FoodPortion
            //Assert.IsInstanceOfType<FoodPortion> (instance, "variable 'instance' is a FoodPortion");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'DataPoints'
        /// </summary>
        [Test]
        public void DataPointsTest()
        {
            // TODO unit test for the property 'DataPoints'
        }
        /// <summary>
        /// Test the property 'GramWeight'
        /// </summary>
        [Test]
        public void GramWeightTest()
        {
            // TODO unit test for the property 'GramWeight'
        }
        /// <summary>
        /// Test the property 'MinYearAcquired'
        /// </summary>
        [Test]
        public void MinYearAcquiredTest()
        {
            // TODO unit test for the property 'MinYearAcquired'
        }
        /// <summary>
        /// Test the property 'Modifier'
        /// </summary>
        [Test]
        public void ModifierTest()
        {
            // TODO unit test for the property 'Modifier'
        }
        /// <summary>
        /// Test the property 'PortionDescription'
        /// </summary>
        [Test]
        public void PortionDescriptionTest()
        {
            // TODO unit test for the property 'PortionDescription'
        }
        /// <summary>
        /// Test the property 'SequenceNumber'
        /// </summary>
        [Test]
        public void SequenceNumberTest()
        {
            // TODO unit test for the property 'SequenceNumber'
        }
        /// <summary>
        /// Test the property 'MeasureUnit'
        /// </summary>
        [Test]
        public void MeasureUnitTest()
        {
            // TODO unit test for the property 'MeasureUnit'
        }

    }

}
