/* 
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FoodNutrient
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FoodNutrientTests
    {
        // TODO uncomment below to declare an instance variable for FoodNutrient
        //private FoodNutrient instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FoodNutrient
            //instance = new FoodNutrient();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FoodNutrient
        /// </summary>
        [Test]
        public void FoodNutrientInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FoodNutrient
            //Assert.IsInstanceOfType<FoodNutrient> (instance, "variable 'instance' is a FoodNutrient");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'DataPoints'
        /// </summary>
        [Test]
        public void DataPointsTest()
        {
            // TODO unit test for the property 'DataPoints'
        }
        /// <summary>
        /// Test the property 'Min'
        /// </summary>
        [Test]
        public void MinTest()
        {
            // TODO unit test for the property 'Min'
        }
        /// <summary>
        /// Test the property 'Max'
        /// </summary>
        [Test]
        public void MaxTest()
        {
            // TODO unit test for the property 'Max'
        }
        /// <summary>
        /// Test the property 'Median'
        /// </summary>
        [Test]
        public void MedianTest()
        {
            // TODO unit test for the property 'Median'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Nutrient'
        /// </summary>
        [Test]
        public void NutrientTest()
        {
            // TODO unit test for the property 'Nutrient'
        }
        /// <summary>
        /// Test the property 'FoodNutrientDerivation'
        /// </summary>
        [Test]
        public void FoodNutrientDerivationTest()
        {
            // TODO unit test for the property 'FoodNutrientDerivation'
        }
        /// <summary>
        /// Test the property 'NutrientAnalysisDetails'
        /// </summary>
        [Test]
        public void NutrientAnalysisDetailsTest()
        {
            // TODO unit test for the property 'NutrientAnalysisDetails'
        }

    }

}
