/* 
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NutrientAcquisitionDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NutrientAcquisitionDetailsTests
    {
        // TODO uncomment below to declare an instance variable for NutrientAcquisitionDetails
        //private NutrientAcquisitionDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NutrientAcquisitionDetails
            //instance = new NutrientAcquisitionDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NutrientAcquisitionDetails
        /// </summary>
        [Test]
        public void NutrientAcquisitionDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NutrientAcquisitionDetails
            //Assert.IsInstanceOfType<NutrientAcquisitionDetails> (instance, "variable 'instance' is a NutrientAcquisitionDetails");
        }


        /// <summary>
        /// Test the property 'SampleUnitId'
        /// </summary>
        [Test]
        public void SampleUnitIdTest()
        {
            // TODO unit test for the property 'SampleUnitId'
        }
        /// <summary>
        /// Test the property 'PurchaseDate'
        /// </summary>
        [Test]
        public void PurchaseDateTest()
        {
            // TODO unit test for the property 'PurchaseDate'
        }
        /// <summary>
        /// Test the property 'StoreCity'
        /// </summary>
        [Test]
        public void StoreCityTest()
        {
            // TODO unit test for the property 'StoreCity'
        }
        /// <summary>
        /// Test the property 'StoreState'
        /// </summary>
        [Test]
        public void StoreStateTest()
        {
            // TODO unit test for the property 'StoreState'
        }

    }

}
