/* 
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NutrientAnalysisDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NutrientAnalysisDetailsTests
    {
        // TODO uncomment below to declare an instance variable for NutrientAnalysisDetails
        //private NutrientAnalysisDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NutrientAnalysisDetails
            //instance = new NutrientAnalysisDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NutrientAnalysisDetails
        /// </summary>
        [Test]
        public void NutrientAnalysisDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NutrientAnalysisDetails
            //Assert.IsInstanceOfType<NutrientAnalysisDetails> (instance, "variable 'instance' is a NutrientAnalysisDetails");
        }


        /// <summary>
        /// Test the property 'SubSampleId'
        /// </summary>
        [Test]
        public void SubSampleIdTest()
        {
            // TODO unit test for the property 'SubSampleId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'NutrientId'
        /// </summary>
        [Test]
        public void NutrientIdTest()
        {
            // TODO unit test for the property 'NutrientId'
        }
        /// <summary>
        /// Test the property 'LabMethodDescription'
        /// </summary>
        [Test]
        public void LabMethodDescriptionTest()
        {
            // TODO unit test for the property 'LabMethodDescription'
        }
        /// <summary>
        /// Test the property 'LabMethodOriginalDescription'
        /// </summary>
        [Test]
        public void LabMethodOriginalDescriptionTest()
        {
            // TODO unit test for the property 'LabMethodOriginalDescription'
        }
        /// <summary>
        /// Test the property 'LabMethodLink'
        /// </summary>
        [Test]
        public void LabMethodLinkTest()
        {
            // TODO unit test for the property 'LabMethodLink'
        }
        /// <summary>
        /// Test the property 'LabMethodTechnique'
        /// </summary>
        [Test]
        public void LabMethodTechniqueTest()
        {
            // TODO unit test for the property 'LabMethodTechnique'
        }
        /// <summary>
        /// Test the property 'NutrientAcquisitionDetails'
        /// </summary>
        [Test]
        public void NutrientAcquisitionDetailsTest()
        {
            // TODO unit test for the property 'NutrientAcquisitionDetails'
        }

    }

}
