/* 
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SampleFoodItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SampleFoodItemTests
    {
        // TODO uncomment below to declare an instance variable for SampleFoodItem
        //private SampleFoodItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SampleFoodItem
            //instance = new SampleFoodItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SampleFoodItem
        /// </summary>
        [Test]
        public void SampleFoodItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SampleFoodItem
            //Assert.IsInstanceOfType<SampleFoodItem> (instance, "variable 'instance' is a SampleFoodItem");
        }


        /// <summary>
        /// Test the property 'FdcId'
        /// </summary>
        [Test]
        public void FdcIdTest()
        {
            // TODO unit test for the property 'FdcId'
        }
        /// <summary>
        /// Test the property 'Datatype'
        /// </summary>
        [Test]
        public void DatatypeTest()
        {
            // TODO unit test for the property 'Datatype'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'FoodClass'
        /// </summary>
        [Test]
        public void FoodClassTest()
        {
            // TODO unit test for the property 'FoodClass'
        }
        /// <summary>
        /// Test the property 'PublicationDate'
        /// </summary>
        [Test]
        public void PublicationDateTest()
        {
            // TODO unit test for the property 'PublicationDate'
        }
        /// <summary>
        /// Test the property 'FoodAttributes'
        /// </summary>
        [Test]
        public void FoodAttributesTest()
        {
            // TODO unit test for the property 'FoodAttributes'
        }

    }

}
