/* 
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SearchResultFood
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SearchResultFoodTests
    {
        // TODO uncomment below to declare an instance variable for SearchResultFood
        //private SearchResultFood instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SearchResultFood
            //instance = new SearchResultFood();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SearchResultFood
        /// </summary>
        [Test]
        public void SearchResultFoodInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SearchResultFood
            //Assert.IsInstanceOfType<SearchResultFood> (instance, "variable 'instance' is a SearchResultFood");
        }


        /// <summary>
        /// Test the property 'FdcId'
        /// </summary>
        [Test]
        public void FdcIdTest()
        {
            // TODO unit test for the property 'FdcId'
        }
        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Test]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'FoodCode'
        /// </summary>
        [Test]
        public void FoodCodeTest()
        {
            // TODO unit test for the property 'FoodCode'
        }
        /// <summary>
        /// Test the property 'FoodNutrients'
        /// </summary>
        [Test]
        public void FoodNutrientsTest()
        {
            // TODO unit test for the property 'FoodNutrients'
        }
        /// <summary>
        /// Test the property 'PublicationDate'
        /// </summary>
        [Test]
        public void PublicationDateTest()
        {
            // TODO unit test for the property 'PublicationDate'
        }
        /// <summary>
        /// Test the property 'ScientificName'
        /// </summary>
        [Test]
        public void ScientificNameTest()
        {
            // TODO unit test for the property 'ScientificName'
        }
        /// <summary>
        /// Test the property 'BrandOwner'
        /// </summary>
        [Test]
        public void BrandOwnerTest()
        {
            // TODO unit test for the property 'BrandOwner'
        }
        /// <summary>
        /// Test the property 'GtinUpc'
        /// </summary>
        [Test]
        public void GtinUpcTest()
        {
            // TODO unit test for the property 'GtinUpc'
        }
        /// <summary>
        /// Test the property 'Ingredients'
        /// </summary>
        [Test]
        public void IngredientsTest()
        {
            // TODO unit test for the property 'Ingredients'
        }
        /// <summary>
        /// Test the property 'NdbNumber'
        /// </summary>
        [Test]
        public void NdbNumberTest()
        {
            // TODO unit test for the property 'NdbNumber'
        }
        /// <summary>
        /// Test the property 'AdditionalDescriptions'
        /// </summary>
        [Test]
        public void AdditionalDescriptionsTest()
        {
            // TODO unit test for the property 'AdditionalDescriptions'
        }
        /// <summary>
        /// Test the property 'AllHighlightFields'
        /// </summary>
        [Test]
        public void AllHighlightFieldsTest()
        {
            // TODO unit test for the property 'AllHighlightFields'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }

    }

}
