/* 
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SearchResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SearchResultTests
    {
        // TODO uncomment below to declare an instance variable for SearchResult
        //private SearchResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SearchResult
            //instance = new SearchResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SearchResult
        /// </summary>
        [Test]
        public void SearchResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SearchResult
            //Assert.IsInstanceOfType<SearchResult> (instance, "variable 'instance' is a SearchResult");
        }


        /// <summary>
        /// Test the property 'FoodSearchCriteria'
        /// </summary>
        [Test]
        public void FoodSearchCriteriaTest()
        {
            // TODO unit test for the property 'FoodSearchCriteria'
        }
        /// <summary>
        /// Test the property 'TotalHits'
        /// </summary>
        [Test]
        public void TotalHitsTest()
        {
            // TODO unit test for the property 'TotalHits'
        }
        /// <summary>
        /// Test the property 'CurrentPage'
        /// </summary>
        [Test]
        public void CurrentPageTest()
        {
            // TODO unit test for the property 'CurrentPage'
        }
        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Test]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }
        /// <summary>
        /// Test the property 'Foods'
        /// </summary>
        [Test]
        public void FoodsTest()
        {
            // TODO unit test for the property 'Foods'
        }

    }

}
