/* 
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.FoodDataCentralSDK.Client.SwaggerDateConverter;
namespace IO.FoodDataCentralSDK.Model
{
    /// <summary>
    /// BrandedFoodItem
    /// </summary>
    [DataContract]
        public partial class BrandedFoodItem :  IEquatable<BrandedFoodItem>, IValidatableObject, InlineResponse200 
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BrandedFoodItem" /> class.
        /// </summary>
        /// <param name="fdcId">fdcId (required).</param>
        /// <param name="availableDate">availableDate.</param>
        /// <param name="brandOwner">brandOwner.</param>
        /// <param name="dataSource">dataSource.</param>
        /// <param name="dataType">dataType (required).</param>
        /// <param name="description">description (required).</param>
        /// <param name="foodClass">foodClass.</param>
        /// <param name="gtinUpc">gtinUpc.</param>
        /// <param name="householdServingFullText">householdServingFullText.</param>
        /// <param name="ingredients">ingredients.</param>
        /// <param name="modifiedDate">modifiedDate.</param>
        /// <param name="publicationDate">publicationDate.</param>
        /// <param name="servingSize">servingSize.</param>
        /// <param name="servingSizeUnit">servingSizeUnit.</param>
        /// <param name="preparationStateCode">preparationStateCode.</param>
        /// <param name="brandedFoodCategory">brandedFoodCategory.</param>
        /// <param name="tradeChannel">tradeChannel.</param>
        /// <param name="gpcClassCode">gpcClassCode.</param>
        /// <param name="foodNutrients">foodNutrients.</param>
        /// <param name="foodUpdateLog">foodUpdateLog.</param>
        /// <param name="labelNutrients">labelNutrients.</param>
        public BrandedFoodItem(int? fdcId = default(int?), string availableDate = default(string), string brandOwner = default(string), string dataSource = default(string), string dataType = default(string), string description = default(string), string foodClass = default(string), string gtinUpc = default(string), string householdServingFullText = default(string), string ingredients = default(string), string modifiedDate = default(string), string publicationDate = default(string), int? servingSize = default(int?), string servingSizeUnit = default(string), string preparationStateCode = default(string), string brandedFoodCategory = default(string), List<string> tradeChannel = default(List<string>), int? gpcClassCode = default(int?), List<FoodNutrient> foodNutrients = default(List<FoodNutrient>), List<FoodUpdateLog> foodUpdateLog = default(List<FoodUpdateLog>), BrandedFoodItemLabelNutrients labelNutrients = default(BrandedFoodItemLabelNutrients))
        {
            // to ensure "fdcId" is required (not null)
            if (fdcId == null)
            {
                throw new InvalidDataException("fdcId is a required property for BrandedFoodItem and cannot be null");
            }
            else
            {
                this.FdcId = fdcId;
            }
            // to ensure "dataType" is required (not null)
            if (dataType == null)
            {
                throw new InvalidDataException("dataType is a required property for BrandedFoodItem and cannot be null");
            }
            else
            {
                this.DataType = dataType;
            }
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new InvalidDataException("description is a required property for BrandedFoodItem and cannot be null");
            }
            else
            {
                this.Description = description;
            }
            this.AvailableDate = availableDate;
            this.BrandOwner = brandOwner;
            this.DataSource = dataSource;
            this.FoodClass = foodClass;
            this.GtinUpc = gtinUpc;
            this.HouseholdServingFullText = householdServingFullText;
            this.Ingredients = ingredients;
            this.ModifiedDate = modifiedDate;
            this.PublicationDate = publicationDate;
            this.ServingSize = servingSize;
            this.ServingSizeUnit = servingSizeUnit;
            this.PreparationStateCode = preparationStateCode;
            this.BrandedFoodCategory = brandedFoodCategory;
            this.TradeChannel = tradeChannel;
            this.GpcClassCode = gpcClassCode;
            this.FoodNutrients = foodNutrients;
            this.FoodUpdateLog = foodUpdateLog;
            this.LabelNutrients = labelNutrients;
        }
        
        /// <summary>
        /// Gets or Sets FdcId
        /// </summary>
        [DataMember(Name="fdcId", EmitDefaultValue=false)]
        public int? FdcId { get; set; }

        /// <summary>
        /// Gets or Sets AvailableDate
        /// </summary>
        [DataMember(Name="availableDate", EmitDefaultValue=false)]
        public string AvailableDate { get; set; }

        /// <summary>
        /// Gets or Sets BrandOwner
        /// </summary>
        [DataMember(Name="brandOwner", EmitDefaultValue=false)]
        public string BrandOwner { get; set; }

        /// <summary>
        /// Gets or Sets DataSource
        /// </summary>
        [DataMember(Name="dataSource", EmitDefaultValue=false)]
        public string DataSource { get; set; }

        /// <summary>
        /// Gets or Sets DataType
        /// </summary>
        [DataMember(Name="dataType", EmitDefaultValue=false)]
        public string DataType { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets FoodClass
        /// </summary>
        [DataMember(Name="foodClass", EmitDefaultValue=false)]
        public string FoodClass { get; set; }

        /// <summary>
        /// Gets or Sets GtinUpc
        /// </summary>
        [DataMember(Name="gtinUpc", EmitDefaultValue=false)]
        public string GtinUpc { get; set; }

        /// <summary>
        /// Gets or Sets HouseholdServingFullText
        /// </summary>
        [DataMember(Name="householdServingFullText", EmitDefaultValue=false)]
        public string HouseholdServingFullText { get; set; }

        /// <summary>
        /// Gets or Sets Ingredients
        /// </summary>
        [DataMember(Name="ingredients", EmitDefaultValue=false)]
        public string Ingredients { get; set; }

        /// <summary>
        /// Gets or Sets ModifiedDate
        /// </summary>
        [DataMember(Name="modifiedDate", EmitDefaultValue=false)]
        public string ModifiedDate { get; set; }

        /// <summary>
        /// Gets or Sets PublicationDate
        /// </summary>
        [DataMember(Name="publicationDate", EmitDefaultValue=false)]
        public string PublicationDate { get; set; }

        /// <summary>
        /// Gets or Sets ServingSize
        /// </summary>
        [DataMember(Name="servingSize", EmitDefaultValue=false)]
        public int? ServingSize { get; set; }

        /// <summary>
        /// Gets or Sets ServingSizeUnit
        /// </summary>
        [DataMember(Name="servingSizeUnit", EmitDefaultValue=false)]
        public string ServingSizeUnit { get; set; }

        /// <summary>
        /// Gets or Sets PreparationStateCode
        /// </summary>
        [DataMember(Name="preparationStateCode", EmitDefaultValue=false)]
        public string PreparationStateCode { get; set; }

        /// <summary>
        /// Gets or Sets BrandedFoodCategory
        /// </summary>
        [DataMember(Name="brandedFoodCategory", EmitDefaultValue=false)]
        public string BrandedFoodCategory { get; set; }

        /// <summary>
        /// Gets or Sets TradeChannel
        /// </summary>
        [DataMember(Name="tradeChannel", EmitDefaultValue=false)]
        public List<string> TradeChannel { get; set; }

        /// <summary>
        /// Gets or Sets GpcClassCode
        /// </summary>
        [DataMember(Name="gpcClassCode", EmitDefaultValue=false)]
        public int? GpcClassCode { get; set; }

        /// <summary>
        /// Gets or Sets FoodNutrients
        /// </summary>
        [DataMember(Name="foodNutrients", EmitDefaultValue=false)]
        public List<FoodNutrient> FoodNutrients { get; set; }

        /// <summary>
        /// Gets or Sets FoodUpdateLog
        /// </summary>
        [DataMember(Name="foodUpdateLog", EmitDefaultValue=false)]
        public List<FoodUpdateLog> FoodUpdateLog { get; set; }

        /// <summary>
        /// Gets or Sets LabelNutrients
        /// </summary>
        [DataMember(Name="labelNutrients", EmitDefaultValue=false)]
        public BrandedFoodItemLabelNutrients LabelNutrients { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BrandedFoodItem {\n");
            sb.Append("  FdcId: ").Append(FdcId).Append("\n");
            sb.Append("  AvailableDate: ").Append(AvailableDate).Append("\n");
            sb.Append("  BrandOwner: ").Append(BrandOwner).Append("\n");
            sb.Append("  DataSource: ").Append(DataSource).Append("\n");
            sb.Append("  DataType: ").Append(DataType).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  FoodClass: ").Append(FoodClass).Append("\n");
            sb.Append("  GtinUpc: ").Append(GtinUpc).Append("\n");
            sb.Append("  HouseholdServingFullText: ").Append(HouseholdServingFullText).Append("\n");
            sb.Append("  Ingredients: ").Append(Ingredients).Append("\n");
            sb.Append("  ModifiedDate: ").Append(ModifiedDate).Append("\n");
            sb.Append("  PublicationDate: ").Append(PublicationDate).Append("\n");
            sb.Append("  ServingSize: ").Append(ServingSize).Append("\n");
            sb.Append("  ServingSizeUnit: ").Append(ServingSizeUnit).Append("\n");
            sb.Append("  PreparationStateCode: ").Append(PreparationStateCode).Append("\n");
            sb.Append("  BrandedFoodCategory: ").Append(BrandedFoodCategory).Append("\n");
            sb.Append("  TradeChannel: ").Append(TradeChannel).Append("\n");
            sb.Append("  GpcClassCode: ").Append(GpcClassCode).Append("\n");
            sb.Append("  FoodNutrients: ").Append(FoodNutrients).Append("\n");
            sb.Append("  FoodUpdateLog: ").Append(FoodUpdateLog).Append("\n");
            sb.Append("  LabelNutrients: ").Append(LabelNutrients).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BrandedFoodItem);
        }

        /// <summary>
        /// Returns true if BrandedFoodItem instances are equal
        /// </summary>
        /// <param name="input">Instance of BrandedFoodItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BrandedFoodItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FdcId == input.FdcId ||
                    (this.FdcId != null &&
                    this.FdcId.Equals(input.FdcId))
                ) && 
                (
                    this.AvailableDate == input.AvailableDate ||
                    (this.AvailableDate != null &&
                    this.AvailableDate.Equals(input.AvailableDate))
                ) && 
                (
                    this.BrandOwner == input.BrandOwner ||
                    (this.BrandOwner != null &&
                    this.BrandOwner.Equals(input.BrandOwner))
                ) && 
                (
                    this.DataSource == input.DataSource ||
                    (this.DataSource != null &&
                    this.DataSource.Equals(input.DataSource))
                ) && 
                (
                    this.DataType == input.DataType ||
                    (this.DataType != null &&
                    this.DataType.Equals(input.DataType))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.FoodClass == input.FoodClass ||
                    (this.FoodClass != null &&
                    this.FoodClass.Equals(input.FoodClass))
                ) && 
                (
                    this.GtinUpc == input.GtinUpc ||
                    (this.GtinUpc != null &&
                    this.GtinUpc.Equals(input.GtinUpc))
                ) && 
                (
                    this.HouseholdServingFullText == input.HouseholdServingFullText ||
                    (this.HouseholdServingFullText != null &&
                    this.HouseholdServingFullText.Equals(input.HouseholdServingFullText))
                ) && 
                (
                    this.Ingredients == input.Ingredients ||
                    (this.Ingredients != null &&
                    this.Ingredients.Equals(input.Ingredients))
                ) && 
                (
                    this.ModifiedDate == input.ModifiedDate ||
                    (this.ModifiedDate != null &&
                    this.ModifiedDate.Equals(input.ModifiedDate))
                ) && 
                (
                    this.PublicationDate == input.PublicationDate ||
                    (this.PublicationDate != null &&
                    this.PublicationDate.Equals(input.PublicationDate))
                ) && 
                (
                    this.ServingSize == input.ServingSize ||
                    (this.ServingSize != null &&
                    this.ServingSize.Equals(input.ServingSize))
                ) && 
                (
                    this.ServingSizeUnit == input.ServingSizeUnit ||
                    (this.ServingSizeUnit != null &&
                    this.ServingSizeUnit.Equals(input.ServingSizeUnit))
                ) && 
                (
                    this.PreparationStateCode == input.PreparationStateCode ||
                    (this.PreparationStateCode != null &&
                    this.PreparationStateCode.Equals(input.PreparationStateCode))
                ) && 
                (
                    this.BrandedFoodCategory == input.BrandedFoodCategory ||
                    (this.BrandedFoodCategory != null &&
                    this.BrandedFoodCategory.Equals(input.BrandedFoodCategory))
                ) && 
                (
                    this.TradeChannel == input.TradeChannel ||
                    this.TradeChannel != null &&
                    input.TradeChannel != null &&
                    this.TradeChannel.SequenceEqual(input.TradeChannel)
                ) && 
                (
                    this.GpcClassCode == input.GpcClassCode ||
                    (this.GpcClassCode != null &&
                    this.GpcClassCode.Equals(input.GpcClassCode))
                ) && 
                (
                    this.FoodNutrients == input.FoodNutrients ||
                    this.FoodNutrients != null &&
                    input.FoodNutrients != null &&
                    this.FoodNutrients.SequenceEqual(input.FoodNutrients)
                ) && 
                (
                    this.FoodUpdateLog == input.FoodUpdateLog ||
                    this.FoodUpdateLog != null &&
                    input.FoodUpdateLog != null &&
                    this.FoodUpdateLog.SequenceEqual(input.FoodUpdateLog)
                ) && 
                (
                    this.LabelNutrients == input.LabelNutrients ||
                    (this.LabelNutrients != null &&
                    this.LabelNutrients.Equals(input.LabelNutrients))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FdcId != null)
                    hashCode = hashCode * 59 + this.FdcId.GetHashCode();
                if (this.AvailableDate != null)
                    hashCode = hashCode * 59 + this.AvailableDate.GetHashCode();
                if (this.BrandOwner != null)
                    hashCode = hashCode * 59 + this.BrandOwner.GetHashCode();
                if (this.DataSource != null)
                    hashCode = hashCode * 59 + this.DataSource.GetHashCode();
                if (this.DataType != null)
                    hashCode = hashCode * 59 + this.DataType.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.FoodClass != null)
                    hashCode = hashCode * 59 + this.FoodClass.GetHashCode();
                if (this.GtinUpc != null)
                    hashCode = hashCode * 59 + this.GtinUpc.GetHashCode();
                if (this.HouseholdServingFullText != null)
                    hashCode = hashCode * 59 + this.HouseholdServingFullText.GetHashCode();
                if (this.Ingredients != null)
                    hashCode = hashCode * 59 + this.Ingredients.GetHashCode();
                if (this.ModifiedDate != null)
                    hashCode = hashCode * 59 + this.ModifiedDate.GetHashCode();
                if (this.PublicationDate != null)
                    hashCode = hashCode * 59 + this.PublicationDate.GetHashCode();
                if (this.ServingSize != null)
                    hashCode = hashCode * 59 + this.ServingSize.GetHashCode();
                if (this.ServingSizeUnit != null)
                    hashCode = hashCode * 59 + this.ServingSizeUnit.GetHashCode();
                if (this.PreparationStateCode != null)
                    hashCode = hashCode * 59 + this.PreparationStateCode.GetHashCode();
                if (this.BrandedFoodCategory != null)
                    hashCode = hashCode * 59 + this.BrandedFoodCategory.GetHashCode();
                if (this.TradeChannel != null)
                    hashCode = hashCode * 59 + this.TradeChannel.GetHashCode();
                if (this.GpcClassCode != null)
                    hashCode = hashCode * 59 + this.GpcClassCode.GetHashCode();
                if (this.FoodNutrients != null)
                    hashCode = hashCode * 59 + this.FoodNutrients.GetHashCode();
                if (this.FoodUpdateLog != null)
                    hashCode = hashCode * 59 + this.FoodUpdateLog.GetHashCode();
                if (this.LabelNutrients != null)
                    hashCode = hashCode * 59 + this.LabelNutrients.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
