/* 
 * Food Data Central API
 *
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.FoodDataCentralSDK.Client.SwaggerDateConverter;
namespace IO.FoodDataCentralSDK.Model
{
    /// <summary>
    /// WweiaFoodCategory
    /// </summary>
    [DataContract]
        public partial class WweiaFoodCategory :  IEquatable<WweiaFoodCategory>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WweiaFoodCategory" /> class.
        /// </summary>
        /// <param name="wweiaFoodCategoryCode">wweiaFoodCategoryCode.</param>
        /// <param name="wweiaFoodCategoryDescription">wweiaFoodCategoryDescription.</param>
        public WweiaFoodCategory(int? wweiaFoodCategoryCode = default(int?), string wweiaFoodCategoryDescription = default(string))
        {
            this.WweiaFoodCategoryCode = wweiaFoodCategoryCode;
            this.WweiaFoodCategoryDescription = wweiaFoodCategoryDescription;
        }
        
        /// <summary>
        /// Gets or Sets WweiaFoodCategoryCode
        /// </summary>
        [DataMember(Name="wweiaFoodCategoryCode", EmitDefaultValue=false)]
        public int? WweiaFoodCategoryCode { get; set; }

        /// <summary>
        /// Gets or Sets WweiaFoodCategoryDescription
        /// </summary>
        [DataMember(Name="wweiaFoodCategoryDescription", EmitDefaultValue=false)]
        public string WweiaFoodCategoryDescription { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WweiaFoodCategory {\n");
            sb.Append("  WweiaFoodCategoryCode: ").Append(WweiaFoodCategoryCode).Append("\n");
            sb.Append("  WweiaFoodCategoryDescription: ").Append(WweiaFoodCategoryDescription).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WweiaFoodCategory);
        }

        /// <summary>
        /// Returns true if WweiaFoodCategory instances are equal
        /// </summary>
        /// <param name="input">Instance of WweiaFoodCategory to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WweiaFoodCategory input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.WweiaFoodCategoryCode == input.WweiaFoodCategoryCode ||
                    (this.WweiaFoodCategoryCode != null &&
                    this.WweiaFoodCategoryCode.Equals(input.WweiaFoodCategoryCode))
                ) && 
                (
                    this.WweiaFoodCategoryDescription == input.WweiaFoodCategoryDescription ||
                    (this.WweiaFoodCategoryDescription != null &&
                    this.WweiaFoodCategoryDescription.Equals(input.WweiaFoodCategoryDescription))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.WweiaFoodCategoryCode != null)
                    hashCode = hashCode * 59 + this.WweiaFoodCategoryCode.GetHashCode();
                if (this.WweiaFoodCategoryDescription != null)
                    hashCode = hashCode * 59 + this.WweiaFoodCategoryDescription.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
